//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.02 at 02:06:25 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nequi.co/message/integration/services/GetPromotionDetail", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package co.nequi.message.integration.services.getpromotiondetail;
